### ISSUE TITLE
I think we need to change order of steps on contributing.md

### ISSUE THREAD

**Issue by jonifallon** [go-away-alan/blogFace-client#7]
Before you begin a NEW feature/fix

1. Ensure your local master branch is up to date with the master branch on GitHub by running git pull origin master.
2. Checkout the master branch. All new features/fixes should be created off of master.

I think #1 and #2 should be reversed.  I followed this without switching to master first, and didn't end up with the most recent changes.

**Comment by andyjzhong** [comment]
We good.
